[package]
name = "test-parachain-adder"
version = "0.9.19"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Test parachain which adds to a number as its state transition"
edition = "2021"
build = "build.rs"

[dependencies]
parachain = { package = "polkadot-parachain", path = "../../", default-features = false, features = [ "wasm-api" ] }
parity-scale-codec = { version = "3.1.2", default-features = false, features = ["derive"] }
sp-std = { git = "https://github.com/peaqnetwork/substrate", default-features = false , branch = "peaq-polkadot-v0.9.19" }
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
dlmalloc = { version = "0.2.3", features = [ "global" ] }

# We need to make sure the global allocator is disabled until we have support of full substrate externalities
sp-io = { git = "https://github.com/peaqnetwork/substrate", default-features = false, features = [ "disable_allocator" ] , branch = "peaq-polkadot-v0.9.19" }

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/peaqnetwork/substrate", branch = "peaq-polkadot-v0.9.19" }

[features]
default = [ "std" ]
std = [
	"parachain/std",
	"sp-std/std",
]
