[package]
name = "relay-substrate-client"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
async-std = { version = "1.6.5", features = ["attributes"] }
async-trait = "0.1.40"
codec = { package = "parity-scale-codec", version = "3.0.0" }
jsonrpsee = { version = "0.8", features = ["macros", "ws-client"] }
log = "0.4.11"
num-traits = "0.2"
rand = "0.7"
serde = { version = "1.0" }
tokio = { version = "1.8", features = ["rt-multi-thread"] }
thiserror = "1.0.26"

# Bridge dependencies

bp-header-chain = { path = "../../primitives/header-chain" }
bp-messages = { path = "../../primitives/messages" }
bp-runtime = { path = "../../primitives/runtime" }
pallet-bridge-messages = { path = "../../modules/messages" }
finality-relay = { path = "../finality" }
relay-utils = { path = "../utils" }

# Substrate Dependencies

frame-support = { git = "https://github.com/peaqnetwork/substrate", branch = "peaq-polkadot-v0.9.19" }
frame-system = { git = "https://github.com/peaqnetwork/substrate", branch = "peaq-polkadot-v0.9.19" }
pallet-balances = { git = "https://github.com/peaqnetwork/substrate", branch = "peaq-polkadot-v0.9.19" }
pallet-transaction-payment = { git = "https://github.com/peaqnetwork/substrate", branch = "peaq-polkadot-v0.9.19" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/peaqnetwork/substrate", branch = "peaq-polkadot-v0.9.19" }
sc-chain-spec = { git = "https://github.com/peaqnetwork/substrate", branch = "peaq-polkadot-v0.9.19" }
sc-rpc-api = { git = "https://github.com/peaqnetwork/substrate", branch = "peaq-polkadot-v0.9.19" }
sc-transaction-pool-api = { git = "https://github.com/peaqnetwork/substrate", branch = "peaq-polkadot-v0.9.19" }
sp-core = { git = "https://github.com/peaqnetwork/substrate", branch = "peaq-polkadot-v0.9.19" }
sp-finality-grandpa = { git = "https://github.com/peaqnetwork/substrate", branch = "peaq-polkadot-v0.9.19" }
sp-rpc = { git = "https://github.com/peaqnetwork/substrate", branch = "peaq-polkadot-v0.9.19" }
sp-runtime = { git = "https://github.com/peaqnetwork/substrate", branch = "peaq-polkadot-v0.9.19" }
sp-storage = { git = "https://github.com/peaqnetwork/substrate", branch = "peaq-polkadot-v0.9.19" }
sp-trie = { git = "https://github.com/peaqnetwork/substrate", branch = "peaq-polkadot-v0.9.19" }
sp-version = { git = "https://github.com/peaqnetwork/substrate", branch = "peaq-polkadot-v0.9.19" }

#[dev-dependencies]
futures = "0.3.7"
